import { ThemeProvider } from 'next-themes';
import './global.css';
import { LanguageProvider } from './language-provider';

export const metadata = {
  title: 'Here Photos',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <LanguageProvider>{children}</LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
