CREATE DATABASE here DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;

USE here;

CREATE TABLE ScanTask (
  id INT AUTO_INCREMENT PRIMARY KEY,
  taskId CHAR(8) NOT NULL UNIQUE,
  status TINYINT NOT NULL DEFAULT 1, -- 1: pending, 2: running, 3: completed, 4: failed
  total INT NOT NULL DEFAULT 0,
  processed INT NOT NULL DEFAULT 0,
  success INT NOT NULL DEFAULT 0,
  failed INT NOT NULL DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE Setting (
  id INT AUTO_INCREMENT PRIMARY KEY,
  `key` CHAR(32) NOT NULL UNIQUE,
  `value` TEXT DEFAULT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE Photo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  photoId CHAR(8) NOT NULL UNIQUE,
  filePath VARCHAR(255) NOT NULL UNIQUE,
  checkSum CHAR(32) NOT NULL,
  blurHash VARCHAR(32) NULL,
  shotTime DATETIME DEFAULT NULL,
  modifiedTime DATETIME NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE Album (
  id INT AUTO_INCREMENT PRIMARY KEY,
  albumId CHAR(8) NOT NULL UNIQUE,
  title CHAR(64) NOT NULL,
  coverId INT NULL,
  pinned BOOLEAN DEFAULT FALSE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (coverId) REFERENCES Photo(id) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE AlbumPhoto (
  albumId INT NOT NULL,
  photoId INT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (albumId, photoId),
  FOREIGN KEY (albumId) REFERENCES Album(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (photoId) REFERENCES Photo(id) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE Thumbnail (
  id INT AUTO_INCREMENT PRIMARY KEY,
  photoId INT NOT NULL,
  filePath VARCHAR(255) NOT NULL,
  variant TINYINT NOT NULL,
  size INT NOT NULL,
  width SMALLINT NOT NULL,
  height SMALLINT NOT NULL,
  format VARCHAR(50) NOT NULL,
  FOREIGN KEY (photoId) REFERENCES Photo(id) ON DELETE CASCADE ON UPDATE CASCADE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE Exif (
  id INT AUTO_INCREMENT PRIMARY KEY,
  photoId INT NOT NULL UNIQUE,
  shotTime DATETIME DEFAULT NULL,
  cameraMake VARCHAR(50) DEFAULT NULL,
  cameraModel VARCHAR(50) DEFAULT NULL,
  iso SMALLINT DEFAULT NULL,
  gpsLatitude FLOAT DEFAULT NULL,
  gpsLongitude FLOAT DEFAULT NULL,
  FOREIGN KEY (photoId) REFERENCES Photo(id) ON DELETE CASCADE ON UPDATE CASCADE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
