import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Share Page',
  description: 'Generated by create next app',
};

export default function ShareLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main>{children}</main>;
}
