import './global.css';

export const metadata = {
  title: 'xxxx',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div id="xxx">{children}</div>
      </body>
    </html>
  );
}
