CREATE DATABASE here DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;

USE here;

SET GLOBAL time_zone = '+00:00'; -- Ensure the time zone is set to UTC

CREATE TABLE QueueTask (
  id INT AUTO_INCREMENT PRIMARY KEY,
  taskId CHAR(8) NOT NULL UNIQUE,
  `type` CHAR(32) NOT NULL,
  `status` CHAR(12) NOT NULL DEFAULT 'pending', -- 'pending', 'running', 'completed', 'failed'
  total INT NOT NULL DEFAULT 0,
  processed INT NOT NULL DEFAULT 0,
  success INT NOT NULL DEFAULT 0,
  failed INT NOT NULL DEFAULT 0,
  skipped INT NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE Setting (
  id INT AUTO_INCREMENT PRIMARY KEY,
  `key` CHAR(32) NOT NULL UNIQUE,
  `value` TEXT DEFAULT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE Photo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  photoId CHAR(8) NOT NULL UNIQUE,
  `hash` CHAR(32) NOT NULL UNIQUE,
  ratio FLOAT NOT NULL, -- width / height
  blurHash VARCHAR(32) NOT NULL,
  birthTime DATETIME NOT NULL,
  modifiedTime DATETIME NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE PhotoFile (
  id INT AUTO_INCREMENT PRIMARY KEY,
  photoId CHAR(8) NOT NULL,
  filePath VARCHAR(255) NOT NULL UNIQUE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (photoId) REFERENCES Photo(photoId) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE Album (
  id INT AUTO_INCREMENT PRIMARY KEY,
  albumId CHAR(8) NOT NULL UNIQUE,
  title CHAR(64) NOT NULL,
  coverId CHAR(8) NULL,
  pinned BOOLEAN NOT NULL DEFAULT FALSE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (coverId) REFERENCES Photo(photoId) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE AlbumPhoto (
  albumId CHAR(8) NOT NULL,
  photoId CHAR(8) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (albumId, photoId),
  FOREIGN KEY (albumId) REFERENCES Album(albumId) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (photoId) REFERENCES Photo(photoId) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE Thumbnail (
  id INT AUTO_INCREMENT PRIMARY KEY,
  photoId CHAR(8) NOT NULL,
  filePath VARCHAR(255) NOT NULL,
  `type` CHAR(2) NOT NULL, -- 'sm', 'md', 'lg'
  `size` INT NOT NULL,
  width SMALLINT NOT NULL,
  height SMALLINT NOT NULL,
  format VARCHAR(50) NOT NULL,
  FOREIGN KEY (photoId) REFERENCES Photo(photoId) ON DELETE CASCADE ON UPDATE CASCADE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE Exif (
  id INT AUTO_INCREMENT PRIMARY KEY,
  photoId CHAR(8) NOT NULL UNIQUE,
  shotTime DATETIME DEFAULT NULL,
  cameraMake VARCHAR(50) DEFAULT NULL,
  cameraModel VARCHAR(50) DEFAULT NULL,
  iso SMALLINT DEFAULT NULL,
  gpsLatitude FLOAT DEFAULT NULL,
  gpsLongitude FLOAT DEFAULT NULL,
  FOREIGN KEY (photoId) REFERENCES Photo(photoId) ON DELETE CASCADE ON UPDATE CASCADE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
